version: '3'


services:
  postgres:
    image: postgres
    env_file:
      - apps/api/.env
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    networks:
      - default
  #  mongo:
  #    image: mongo:latest
  #    env_file:
  #      - ./apps/api/.env
  #    ports:
  #      - "27017:27017"
  #    restart: always
  #    networks:
  #      - default
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./apps/api/.env
    ports:
      - "8080:8080"
    restart: always
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"