# push on apps/snv
on:
  workflow_dispatch:
    branches:
      - main
      - dev
  push:
    branches:
      - main
name: Sync snv Epitech SVn
jobs:
  sync:
    name: Sync with SVN Repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SVN
        run: sudo apt-get install subversion rsync
      - name: Cloning Reposity & Sync
        run: svn checkout ${{secrets.SVN_REPO_ROOT_URL}} sync/snv --username ${{secrets.SVN_USERNAME}} --password ${{secrets.SVN_PASSWORD}};
      - name: Copy files
        run: chmod +x svn-sync-shell.sh; ./svn-sync-shell.sh sync/snv/trunk;
      - name: Added to SVN
        run: svn add --force sync/snv/trunk/*
      - name: Commit
        run: svn commit -m "Sync with SVN Repository" sync/snv/
      - name: Update
        run: svn update sync/snv/
