# push on apps/rendu
on:
  workflow_dispatch:
    branches:
      - main
      - dev
  push:
    paths:
      - apps/rendu
    branches:
      - main
name: Sync Rendu Epitech SVn
jobs:
  sync:
    name: Sync with SVN Repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install git-svn
        run: sudo apt-get install subversion
      - name: Sync with SVN Repository
        run: svn clone -s ${{SVN_REPO_ROOT_URL}} sync/rendu # Is this ok ?
      - name: Sync with SVN Repository
        run: cp -r apps/rendu/* sync/rendu/rendu
      - name: Sync with SVN Repository
        run: svn add sync/rendu/rendu
      - name: Sync with SVN Repository
        run: svn commit -m "Sync with SVN Repository" sync/rendu/
      - name: Sync with SVN Repository
        run: svn update sync/rendu/
