# push on apps/snv
on:
  workflow_dispatch:
    branches:
      - main
      - dev
  push:
    branches:
      - main
name: Sync snv Epitech SVn
jobs:
  sync:
    name: Sync with SVN Repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SVN
        run: sudo apt-get install subversion
      - name: Cloning Reposity & Sync
        run: svn checkout ${{secrets.SVN_REPO_ROOT_URL}} sync/snv --username ${{secrets.SVN_USERNAME}} --password ${{secrets.SVN_PASSWORD}}; \
          rsync -av --ignore-existing --progress . /sync/snv/trunk
      - run: ls -alR sync
      - name: Added to SVN
        run: svn add sync/snv/trunk
      - name: Commit
        run: svn commit -m "Sync with SVN Repository" sync/snv/
      - name: Update
        run: svn update sync/snv/
