on:
  workflow_dispatch:
    branches:
      - main
      - dev
  push:
    paths:
      - apps/website
    branches:
      - main
name: Sync website Epitech SVn
jobs:
  sync:
    name: Sync with SVN Repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install git-svn
        run: sudo apt-get install subversion
      - name: Sync with SVN Repository
        run: svn checkout ${{secrets.SVN_REPO_ROOT_URL}} sync/website --username ${{secrets.SVN_USERNAME}} --password ${{secrets.SVN_PASSWORD}}
      - name: Sync with SVN Repository
        run: cp -r apps/website/* sync/website/www
      - name: Sync with SVN Repository
        run: svn add --force sync/website/www/*
      - name: Sync with SVN Repository
        run: svn commit -m "Sync with SVN Repository" sync/website/ --username ${{secrets.SVN_USERNAME}} --password ${{secrets.SVN_PASSWORD}}
      - name: Sync with SVN Repository
        run: svn update sync/website/ --username ${{secrets.SVN_USERNAME}} --password ${{secrets.SVN_PASSWORD}}
